---
title: ""
output: 
  html_document:
    collapsed: false
    number_sections: false
    toc_depth: 3
    css: front.css


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 1px;
}

</style>

<div class="row" style="padding-top: 50px;">
<div class="col-sm-7">

| Education | |
|:--------|-------:|

<p>PhD Student- Quantitative Methods (University of Pennsylvania) </br>
<p2> *full funding through Dean's Fellowship </br> </p>
Masters Degree - Quantitative Methods (University of Texas at Austin) </br>
Bachelors Degree - Business (University of Notre Dame) 





|Research Area |  |
|:--------|-------:|

My work focuses on the methodological considerations of 
advanced statistics and analytics, particularly those related to observational studies where the treatment is not randomized. For instance, how do the results of an analysis on a nonrandom sample generalize to a larger
population of interest? Where can sampling and stratification approaches improve causal inference estimation? How might a machine learning approach be applied in the framework of an observational study to improve propensity score estimation? 

Prior to pursuing graduate studies, I taught elementary school in the South Bronx with the <a href="https://nycteachingfellows.org/" target = "_blank">New York City Teaching Fellows</a> and in Austin, Texas with the <a href="https://www.kipp.org/kipp-foundation/" target = "_blank">KIPP</a> public charter school network. The four years I spent in the classroom inform much of the applied work in education that I pursue with my doctoral advisor, <a href="https://www.gse.upenn.edu/academics/faculty-directory/chan" target = "_blank">Wendy Chan</a>.

Additionally, I work on analytics consulting and data science projects with the <a href="https://analytics.wharton.upenn.edu/" target = "_blank">Wharton Analytics</a> department, and am pursuing a <a href="https://statistics.wharton.upenn.edu/programs/dual-masters/" target = "_blank">dual Masters degree</a> in Statistics through the Wharton School.

|Technical |  |
|:--------|-------:|

Back End Data Analysis: Python, R, SQL </br>
Front End Visualization: JavaScript (D3.js), CSS, HTML </br>
Version Control: Git/GitHub

|Methodological |  |
|:--------|-------:|

Causal Inference, Bayesian Statistics, Machine Learning, Multilevel Modeling, Structural Equation Modeling, Factor Analysis, Psychometrics, Data Mining, Data Visualization

| Teaching |  |
|:--------|-------:|
Graduate Instructor - (UT Austin)

Programming Instructor - Swift/Xcode (<a href="https://www.helloworldstudio.org/home" target = "_blank">Khan Lab School</a>) </br>

Programming Instructor - R (<a href="https://wharton-moneyball.github.io/index.html" target = "_blank">Wharton Moneyball Academy</a>)

Teacher (Americorps New York City Teaching Fellows, KIPP)


